SELECT   ZC6_OC,  ZC6_CANAL,   ACY_DESCRI,   ZC6_LOCAL,   ZC6_DLOCAL,   ZC6_INTCOD,
   					 	ZC6_INTDES,    SUM(ZC6_CANT) AS ZC6_CANT,    ZC6_PRCVEN,    SUM(ZC6_VALOR) AS ZC6_VALOR
					FROM 
						ZC6010 Z LEFT JOIN  ACY010 A ON Z.ZC6_CANAL = A.ACY_GRPVEN
					WHERE 	ZC6_FILIAL = '01' 
						AND ZC6_CANAL = '4001'
						AND ZC6_INTCOD LIKE '%%'
						AND ZC6_FEMIS BETWEEN '20240801' AND '20241114'
						AND Z.D_E_L_E_T_ <> '*'
					GROUP BY 
						ZC6_OC,ZC6_CANAL,ACY_DESCRI,ZC6_LOCAL,ZC6_DLOCAL,ZC6_INTCOD,ZC6_INTDES,ZC6_PRCVEN
					ORDER BY ZC6_OC,ZC6_INTCOD